services:
  prediction:
    build:
      context: .
      dockerfile: ./apps/predictions/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev predictions
    env_file:
      - ./apps/predictions/.env
    ports:
      - '3001:3001'
