{{- if .Values.ingress.enabled -}}
{{- $fullName := include "trydeploy.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "trydeploy.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          {{- with .Values.ingress.paths }}
          {{- range . }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ printf "%s-%s" .service.name "http" }}
                port:
                  number: {{ .service.portNumber }}
          {{- end }}
          {{- end }}
{{- end }}
